function runTest() {
  throw "exception!"

  return "Exception thrown";
}
